fix: Ensure that the container name is not empty
This extra conditional ensures that the container name is not an empty
string.

diff --git a/inventory b/inventory
--- a/inventory
+++ b/inventory
@@ -9,6 +9,10 @@ fi
 case "$1" in
   add)
     read -r -p "Container: " container
+    if [ -z "$container" ]; then
+      echo "Container cannot be empty"
+      exit 1
+    fi
 
     while true; do
       read -r -p "Item: " item
